CABLE_TYPE_FILTERS = [
    {
        "id": "61",
        "name": "Single-Strand",
        "count": "0",
        "filterChecked": "true",
        "filtername": "cableType",
    },
    {
        "id": "1",
        "name": "N/A (Incl AOC and DAC)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "cableType",
    },
    {
        "id": "2",
        "name": "Duplex Fiber",
        "count": "0",
        "filterChecked": "true",
        "filtername": "cableType",
    },
    {
        "id": "3",
        "name": "Ribbon Fiber",
        "count": "0",
        "filterChecked": "true",
        "filtername": "cableType",
    },
    {
        "id": "5",
        "name": "Single-strand",
        "count": "0",
        "filterChecked": "true",
        "filtername": "cableType",
    },
    {
        "id": 6,
        "name": "Cat5e/6A",
        "count": 0,
        "filterChecked": "true",
        "filtername": "cableType"
    },
]

DATA_RATE_FILTERS = [
    {
        "id": "141",
        "name": "100/200 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "81",
        "name": "10/25 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "1",
        "name": "100 Mbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "2",
        "name": "155 Mbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "3",
        "name": "622 Mbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "4",
        "name": "2.488 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "5",
        "name": "40/100 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "6",
        "name": "40 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "7",
        "name": "100 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "9",
        "name": "25 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "10",
        "name": "10 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": 21,
        "name": "10/100/1000 Mbps",
        "count": 0,
        "filterChecked": "true",
        "filtername": "dataRate"
    },
    {
        "id": "121",
        "name": "8 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "122",
        "name": "16 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
    {
        "id": "123",
        "name": "32 Gbps",
        "count": "0",
        "filterChecked": "true",
        "filtername": "dataRate",
    },
]

FORM_FACTOR_FILTERS = [
    {
        "id": "41",
        "name": "SFP+",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "42",
        "name": "SFP28",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "2",
        "name": "SFP",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "5",
        "name": "QSFP28",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "7",
        "name": "GBIC",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "8",
        "name": "XENPAK",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "9",
        "name": "X2",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "10",
        "name": "XFP",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
    {
        "id": "21",
        "name": "QSFP+",
        "count": "0",
        "filterChecked": "true",
        "filtername": "formFactor",
    },
]

REACH_FILTERS = [
    {
        "id": "2",
        "name": "100m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "81",
        "name": "220m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "141",
        "name": "400m (OM3)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "181",
        "name": "550m (OM3)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "182",
        "name": "10Km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "183",
        "name": "1km (OM4)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "41",
        "name": "4m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "3",
        "name": "1km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "4",
        "name": "550m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "5",
        "name": "70km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "6",
        "name": "80km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "8",
        "name": "70m (OM3)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "9",
        "name": "100m (OM4)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "10",
        "name": "500m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "11",
        "name": "25m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "12",
        "name": "30m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "13",
        "name": "25km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "14",
        "name": "100m (OM3)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "15",
        "name": "300m (OM3)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "16",
        "name": "150m (OM4)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "17",
        "name": "400m (OM4)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "18",
        "name": "10km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "19",
        "name": "40km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "20",
        "name": "2km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "21",
        "name": "5m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "22",
        "name": "3m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "23",
        "name": "1m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "24",
        "name": "7m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "25",
        "name": "10m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "26",
        "name": "2m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "27",
        "name": "15m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "28",
        "name": "20m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "29",
        "name": "None",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "31",
        "name": "15km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "32",
        "name": "20km",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "35",
        "name": "300m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "36",
        "name": "400m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "38",
        "name": "2.5m",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "121",
        "name": "400m (O43)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
    {
        "id": "161",
        "name": "190m (OM4)",
        "count": "0",
        "filterChecked": "true",
        "filtername": "reach",
    },
]

OS_TYPE_FILTERS = [
    {
        "id": "1",
        "name": "NX-OS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "3",
        "name": "IOS XE",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "11",
        "name": "IOS XR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "15",
        "name": "SPA",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "26",
        "name": "IE1000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "48",
        "name": "IOS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "55",
        "name": "UCS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "56",
        "name": "FXOS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "57",
        "name": "OLT",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "60",
        "name": "NAM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "61",
        "name": "SCP",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "101",
        "name": "CatOS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "121",
        "name": "EPA",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "141",
        "name": "WLC",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
    {
        "id": "181",
        "name": "IOS XR 64 Bit",
        "count": "0",
        "filterChecked": "true",
        "filtername": "osType",
    },
]

XCVR_PRODUCT_FAMILY_FILTERS = [
    {
        "id": "41",
        "name": "NCS5500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "1",
        "name": "SFP25G",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "2",
        "name": "SFPOCX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "3",
        "name": "QSFP40G",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "5",
        "name": "QSFP100",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "8",
        "name": "SFPFE",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "10",
        "name": "WDM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "11",
        "name": "SFPGE",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "12",
        "name": "SFP10G",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "13",
        "name": "XENPAK",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "14",
        "name": "X2",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "15",
        "name": "XFP",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
    {
        "id": "21",
        "name": "MDS9000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductFamily",
    },
]

XCVR_PRODUCT_ID_FILTERS = [
    {
        "id": "1",
        "name": "QSFP-100G-SR4-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "2",
        "name": "QSFP-100G-CWDM4-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "3",
        "name": "QSFP-100G-PSM4-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "4",
        "name": "QSFP-100G-LR4-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "5",
        "name": "QSFP-100G-SM-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "6",
        "name": "QSFP-100G-ER4L-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "7",
        "name": "QSFP-40/100-SRBD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "10",
        "name": "QSFP-100G-CU1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "11",
        "name": "QSFP-100G-CU2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "12",
        "name": "QSFP-100G-CU3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "13",
        "name": "QSFP-100G-CU5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "14",
        "name": "QSFP-4SFP25G-CU1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "15",
        "name": "QSFP-4SFP25G-CU2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "16",
        "name": "QSFP-4SFP25G-CU3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "17",
        "name": "QSFP-4SFP25G-CU5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "18",
        "name": "QSFP-100G-AOC1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "19",
        "name": "QSFP-100G-AOC2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "20",
        "name": "QSFP-100G-AOC3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "21",
        "name": "QSFP-100G-AOC5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "22",
        "name": "QSFP-100G-AOC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "23",
        "name": "QSFP-100G-AOC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "24",
        "name": "QSFP-100G-AOC15M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "25",
        "name": "QSFP-100G-AOC20M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "26",
        "name": "QSFP-100G-AOC25M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "27",
        "name": "QSFP-100G-AOC30M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "31",
        "name": "CPAK-100G-SR10",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "32",
        "name": "CPAK-100G-ER4L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "33",
        "name": "CPAK-100G-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "34",
        "name": "CPAK-10X10G-LR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "35",
        "name": "CPAK-10X10G-ERL",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "36",
        "name": "CPAK-100G-SR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "37",
        "name": "CPAK-100G-CWDM4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "38",
        "name": "CPAK-100G-PSM4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "39",
        "name": "GLC-FE-100FX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "40",
        "name": "GLC-GE-100FX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "41",
        "name": "GLC-FE-100LX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "42",
        "name": "GLC-FE-100EX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "43",
        "name": "GLC-FE-100ZX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "44",
        "name": "GLC-FE-100BX-D",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "45",
        "name": "GLC-FE-100BX-U",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "46",
        "name": "GLC-FE-T-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "47",
        "name": "GLC-FE-100FX-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "48",
        "name": "GLC-FE-100LX-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "49",
        "name": "SFP-OC3-MM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "50",
        "name": "SFP-OC3-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "51",
        "name": "SFP-OC3-IR1",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "52",
        "name": "SFP-OC3-LR1",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "53",
        "name": "SFP-OC3-LR2",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "54",
        "name": "SFP-OC12-MM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "55",
        "name": "SFP-OC12-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "56",
        "name": "SFP-OC12-IR1",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "57",
        "name": "SFP-OC12-LR1",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "58",
        "name": "SFP-OC12-LR2",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "59",
        "name": "SFP-OC48-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "60",
        "name": "SFP-OC48-IR1",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "61",
        "name": "SFP-OC48-LR2",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "62",
        "name": "SFP-H25G-CU1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "63",
        "name": "SFP-H25G-CU2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "64",
        "name": "SFP-H25G-CU3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "65",
        "name": "SFP-H25G-CU5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "66",
        "name": "SFP-25G-AOC1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "67",
        "name": "SFP-25G-AOC2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "68",
        "name": "SFP-25G-AOC3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "69",
        "name": "SFP-25G-AOC5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "70",
        "name": "SFP-25G-AOC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "71",
        "name": "SFP-25G-AOC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "72",
        "name": "SFP-25G-SR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "73",
        "name": "SFP-10G-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "74",
        "name": "SFP-10G-SR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "75",
        "name": "SFP-10G-SR-X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "76",
        "name": "SFP-10G-LRM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "77",
        "name": "SFP-10G-LR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "78",
        "name": "SFP-10G-LR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "79",
        "name": "SFP-10G-LR-X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "80",
        "name": "SFP-10G-ER",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "81",
        "name": "SFP-10G-ER-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "82",
        "name": "SFP-10G-ZR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "83",
        "name": "SFP-10G-ZR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "84",
        "name": "SFP-10G-BXD-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "85",
        "name": "SFP-10G-BXU-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "86",
        "name": "SFP-10G-BX40D-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "87",
        "name": "SFP-10G-BX40U-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "88",
        "name": "SFP-H10GB-CU1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "89",
        "name": "SFP-H10GB-CU3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "90",
        "name": "SFP-H10GB-CU5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "91",
        "name": "SFP-H10GB-ACU7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "92",
        "name": "SFP-H10GB-ACU10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "93",
        "name": "SFP-10G-AOC1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "94",
        "name": "SFP-10G-AOC2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "95",
        "name": "SFP-10G-AOC3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "96",
        "name": "SFP-10G-AOC5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "97",
        "name": "SFP-10G-AOC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "98",
        "name": "SFP-10G-AOC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "99",
        "name": "FET-10G",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "100",
        "name": "DWDM-SFP10G-61.41",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "101",
        "name": "DWDM-SFP10G-XX.XX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "102",
        "name": "CWDM-SFP10G-XXXX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "103",
        "name": "XENPAK-10GB-ER",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "104",
        "name": "XENPAK-10GB-ER+",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "105",
        "name": "XENPAK-10GB-LR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "106",
        "name": "XENPAK-10GB-LR+",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "107",
        "name": "XENPAK-10GB-LRM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "108",
        "name": "XENPAK-10GB-LW",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "109",
        "name": "XENPAK-10GB-LX4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "110",
        "name": "XENPAK-10GB-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "111",
        "name": "XENPAK-10GB-CX4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "112",
        "name": "XENPAK-10GB-ZR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "113",
        "name": "DWDM-XENPAK-XX.XX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "114",
        "name": "X2-10GB-LR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "115",
        "name": "X2-10GB-ER",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "116",
        "name": "X2-10GB-ZR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "117",
        "name": "X2-10GB-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "118",
        "name": "X2-10GB-CX4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "119",
        "name": "X2-10GB-LX4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "120",
        "name": "X2-10GB-LRM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "121",
        "name": "X2-10GB-T",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "122",
        "name": "DWDM-X2-XX.XX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "123",
        "name": "XFP-10GLR-OC192SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "124",
        "name": "XFP10GLR-192SR-L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "125",
        "name": "XFP-10GER-OC192IR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "126",
        "name": "XFP-10GER-192IR+",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "127",
        "name": "XFP10GER-192IR-L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "128",
        "name": "XFP-10GZR-OC192LR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "129",
        "name": "XFP-10G-MM-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "130",
        "name": "XFP10GLR192SR-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "131",
        "name": "XFP10GER192IR-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "132",
        "name": "XFP10GZR192LR-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "133",
        "name": "DWDM-XFP-XX.XX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "134",
        "name": "DWDM-XFP-C",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "135",
        "name": "WS-G5483",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "136",
        "name": "WS-G5484",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "137",
        "name": "WS-G5486",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "138",
        "name": "WS-G5487",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "139",
        "name": "CWDM-GBIC-XXXX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "140",
        "name": "GLC-T",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "141",
        "name": "GLC-TE",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "142",
        "name": "GLC-SX-MM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "143",
        "name": "GLC-LH-SM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "144",
        "name": "GLC-ZX-SM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "145",
        "name": "GLC-BX-D",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "146",
        "name": "GLC-BX-U",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "147",
        "name": "QSFP-40G-SR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "148",
        "name": "QSFP-40G-CSR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "149",
        "name": "QSFP-40G-SR4-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "150",
        "name": "FET-40G",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "151",
        "name": "QSFP-40G-SR-BD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "152",
        "name": "QSFP-4X10G-LR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "153",
        "name": "QSFP-40G-LR4-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "154",
        "name": "QSFP-40GE-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "155",
        "name": "QSFP-40G-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "156",
        "name": "QSFP-40G-ER4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "157",
        "name": "WSP-Q40GLR4L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "158",
        "name": "QSFP-4SFP10G-CU5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "159",
        "name": "QSFP-4SFP10G-CU3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "160",
        "name": "QSFP-4SFP10G-CU1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "161",
        "name": "QSFP-4X10G-AC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "162",
        "name": "QSFP-4X10G-AC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "163",
        "name": "QSFP-H40G-CU5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "164",
        "name": "QSFP-H40G-CU3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "165",
        "name": "QSFP-H40G-CU1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "166",
        "name": "QSFP-H40G-ACU7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "167",
        "name": "QSFP-H40G-ACU10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "168",
        "name": "QSFP-4X10G-AOC1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "169",
        "name": "QSFP-4X10G-AOC2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "170",
        "name": "QSFP-4X10G-AOC3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "171",
        "name": "QSFP-4X10G-AOC5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "172",
        "name": "QSFP-4X10G-AOC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "173",
        "name": "QSFP-4X10G-AOC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "174",
        "name": "QSFP-H40G-AOC1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "175",
        "name": "QSFP-H40G-AOC2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "176",
        "name": "QSFP-H40G-AOC3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "177",
        "name": "QSFP-H40G-AOC5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "178",
        "name": "QSFP-H40G-AOC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "179",
        "name": "QSFP-H40G-AOC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "180",
        "name": "QSFP-H40G-AOC15M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "181",
        "name": "QSFP-H40G-AOC20M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "183",
        "name": "CVR-CFP-4SFP10G",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "184",
        "name": "CFP-40G-SR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "185",
        "name": "CFP-40G-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "301",
        "name": "QSFP-4x10G-AC7M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "302",
        "name": "QSFP-4x10G-AC10M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "361",
        "name": "QSFP-H40G-CU0-5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "362",
        "name": "QSFP-H40G-CU2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "363",
        "name": "QSFP-H40G-CU4M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "441",
        "name": "DWDM-SFP10G-C-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "621",
        "name": "MA-SFP-1GB-LX10",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "622",
        "name": "MA-SFP-1GB-SX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "623",
        "name": "MA-SFP-1GB-TX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "624",
        "name": "MA-CBL-40G-1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "625",
        "name": "MA-CBL-40G-3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "626",
        "name": "MA-CBL-40G-50CM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "627",
        "name": "MA-CBL-TA-1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "628",
        "name": "MA-CBL-TA-3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "629",
        "name": "MA-SFP-10GB-LR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "630",
        "name": "MA-SFP-10GB-LRM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "631",
        "name": "MA-SFP-10GB-SR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "632",
        "name": "MA-CBL-100G-1M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "633",
        "name": "MA-CBL-100G-3M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "634",
        "name": "MA-CBL-100G-50CM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "635",
        "name": "MA-QSFP-40G-CSR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "636",
        "name": "MA-QSFP-40G-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "637",
        "name": "MA-QSFP-40G-SR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "638",
        "name": "MA-QSFP-40G-SR-BD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "639",
        "name": "MA-QSFP-100G-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "640",
        "name": "MA-QSFP-100G-SR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "281",
        "name": "QSFP-4X10G-AOC15M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "401",
        "name": "QSFP-4x10G-LR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "402",
        "name": "SFP-10/25G-LR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "421",
        "name": "CVR-4SFP10G-QSFP",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "481",
        "name": "QSFP-40G-CSR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "581",
        "name": "DWDM-SFP-3268",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "582",
        "name": "DWDM-SFP-3190",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "583",
        "name": "DWDM-SFP-3112",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "584",
        "name": "DWDM-SFP-3033",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "601",
        "name": "CWDM-SFP-1470",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "602",
        "name": "CWDM-SFP-1610",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "641",
        "name": "GLC-BX-D-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "642",
        "name": "GLC-BX-U-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "187",
        "name": "GLC-BX40-D-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "188",
        "name": "GLC-BX40-U-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "189",
        "name": "GLC-BX80-D-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "190",
        "name": "GLC-BX80-U-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "191",
        "name": "GLC-BX40-DA-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "192",
        "name": "GLC-2BX-D",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "193",
        "name": "SFP-GE-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "194",
        "name": "SFP-GE-L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "195",
        "name": "GLC-EX-SMD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "196",
        "name": "SFP-GE-Z",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "197",
        "name": "SFP-GE-T",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "198",
        "name": "GLC-SX-MM-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "199",
        "name": "GLC-LX-SM-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "200",
        "name": "GLC-ZX-SM-RGD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "201",
        "name": "GLC-SX-MMD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "202",
        "name": "GLC-LH-SMD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "203",
        "name": "GLC-ZX-SMD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "204",
        "name": "SFP-GPON-B",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "205",
        "name": "SFP-GPON-B-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "206",
        "name": "SFP-GPON-C",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "207",
        "name": "SFP-GPON-C-I",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "208",
        "name": "CWDM-SFP-XXXX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "209",
        "name": "DWDM-SFP-XXXX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "210",
        "name": "QSFP-40G-BD-RX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "211",
        "name": "QSFP-H40G-AOC25M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "212",
        "name": "QSFP-H40G-AOC30M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "213",
        "name": "CPAK-100GE-LR4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "214",
        "name": "CXP-100G-SR10",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "215",
        "name": "CXP-100G-SR12",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "216",
        "name": "CFP2-100G-ER4",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "217",
        "name": "SFP10G-USR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "218",
        "name": "SFP-H10GB-CU1-5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "219",
        "name": "SFP-H10GB-CU2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "220",
        "name": "SFP-H10GB-CU2-5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "221",
        "name": "GLC-GE-DR-LX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "222",
        "name": "DWDM-SFP10G-30.33",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "223",
        "name": "DWDM-SFP10G-C",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "321",
        "name": "SFP-10/25G-CSR-S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "521",
        "name": "CWDM-SFP10G-1530",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "541",
        "name": "SFP-H10GB-CU4M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "561",
        "name": "DS-SFP-FC8G-SW",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "562",
        "name": "DS-SFP-FC16G-SW",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "563",
        "name": "DS-SFP-FC32G-SW",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "661",
        "name": "CFP2-WDM-DET-1HL",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "662",
        "name": "CFP2-WDM-D-1HL",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "461",
        "name": "SFP-25G-AOC4M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "241",
        "name": "QSFP-4SFP10G-CU2M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "242",
        "name": "QSFP-4SFP10G-CU4M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
    {
        "id": "502",
        "name": "QSFP-4SFP10G-CU0-5M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "transceiverProductID",
    },
]

NETWORK_DEVICE_PRODUCT_FAMILY_FILTERS = [
    {
        "id": "1",
        "name": "C2960P",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "2",
        "name": "C2960S",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "3",
        "name": "C2960SF",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "4",
        "name": "C2960C",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "5",
        "name": "C2960X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "6",
        "name": "C2960XR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "7",
        "name": "C9400",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "8",
        "name": "C9500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "9",
        "name": "N3500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "10",
        "name": "N2000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "11",
        "name": "N5000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "12",
        "name": "N6000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "13",
        "name": "N7000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "14",
        "name": "UCSB",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "15",
        "name": "UCSC",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "16",
        "name": "CRS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "17",
        "name": "NCS1000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "19",
        "name": "NCS5000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "20",
        "name": "NCS5500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "21",
        "name": "NCS6000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "22",
        "name": "FPRHIGH",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "23",
        "name": "FPRUHI",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "24",
        "name": "NCS4000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "25",
        "name": "CE500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "26",
        "name": "CE520",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "27",
        "name": "ME2400",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "28",
        "name": "ME3750",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "29",
        "name": "C4KTOR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "30",
        "name": "L3FIXED",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "31",
        "name": "C2900",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "32",
        "name": "DSBUOTH",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "33",
        "name": "C2940",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "34",
        "name": "C2950",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "35",
        "name": "C2960L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "36",
        "name": "C2960CX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "37",
        "name": "C2970",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "38",
        "name": "C2975",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "39",
        "name": "C3550",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "40",
        "name": "C3560CX",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "41",
        "name": "C4000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "42",
        "name": "C6500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "44",
        "name": "C6800",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "45",
        "name": "C2350",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "46",
        "name": "C2360",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "47",
        "name": "OS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "48",
        "name": "N4000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "49",
        "name": "CSS",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "55",
        "name": "ERBUOLD",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "56",
        "name": "UBR7200",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "57",
        "name": "7300",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "58",
        "name": "7304",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "59",
        "name": "7500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "60",
        "name": "ESR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "61",
        "name": "UBR10K",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "62",
        "name": "RFGW10",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "63",
        "name": "GSR",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "64",
        "name": "ASR900",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "65",
        "name": "RANTRAN",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "66",
        "name": "ASAMID",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "67",
        "name": "EMBUNAM",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "68",
        "name": "AIRCTU",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "69",
        "name": "FPRMID",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "70",
        "name": "SCP",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "71",
        "name": "N9000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "72",
        "name": "C4900",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "73",
        "name": "C4900M",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "121",
        "name": "NCS540",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "141",
        "name": "NCS560",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "181",
        "name": "ISR3900",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "182",
        "name": "ISR4000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "183",
        "name": "ISR2900",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "241",
        "name": "AIRCTI2",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "261",
        "name": "ASAHIGH",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "341",
        "name": "C9200",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "342",
        "name": "C9200L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "161",
        "name": "CBR8",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "421",
        "name": "ISR800",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "521",
        "name": "C9600",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "541",
        "name": "MS120 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "542",
        "name": "MS210 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "543",
        "name": "MS225 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "544",
        "name": "MS250 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "545",
        "name": "MS350 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "546",
        "name": "MS355 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "547",
        "name": "MS410 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "548",
        "name": "MS425 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "550",
        "name": "MX84",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "551",
        "name": "MX100",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "552",
        "name": "MX250",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "553",
        "name": "MX400",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "554",
        "name": "MX450",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "555",
        "name": "MX600",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "561",
        "name": "MS450 Series",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "601",
        "name": "C9300L",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "641",
        "name": "ME1200",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "681",
        "name": "C9800",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "701",
        "name": "RPHYSHF",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "721",
        "name": "IE3200",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "722",
        "name": "IE3300",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "723",
        "name": "IE3400",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "74",
        "name": "N9300",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "75",
        "name": "N3000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "76",
        "name": "C9300",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "77",
        "name": "N9500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "78",
        "name": "N9200",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "79",
        "name": "IPACCES",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "82",
        "name": "WANLAN",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "83",
        "name": "ASR9000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "84",
        "name": "800BB",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "88",
        "name": "C6000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "89",
        "name": "7600",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "90",
        "name": "ASR1000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "91",
        "name": "ASR903",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "92",
        "name": "ASR901",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "93",
        "name": "ASR920",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "94",
        "name": "NCS4200",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "97",
        "name": "C3750",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "98",
        "name": "ME3400",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "99",
        "name": "ME2600X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "100",
        "name": "ME3600X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "101",
        "name": "ME3800X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "102",
        "name": "ME4600",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "103",
        "name": "C4500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "104",
        "name": "C4500X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "105",
        "name": "IE1000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "106",
        "name": "IE2000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "107",
        "name": "IE3000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "108",
        "name": "IE4000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "109",
        "name": "IE5000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "110",
        "name": "CGS2500",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "111",
        "name": "CGR2000",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "112",
        "name": "C3850",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "114",
        "name": "C3750X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "115",
        "name": "C3650",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "116",
        "name": "C3560",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "117",
        "name": "C3560C",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "118",
        "name": "C3560X",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "119",
        "name": "C2960",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
    {
        "id": "741",
        "name": "N7700",
        "count": "0",
        "filterChecked": "true",
        "filtername": "networkDeviceProductFamily",
    },
]
